### ISSUE TITLE
Exception: No qualifying bean of type [website.fedulov.Main] is defined

### ISSUE THREAD

**Issue by mikezang** [afedulov/routing-data-source#1]
Hi
I tried your sample, when I run it I got error as below, how can I do next? Can you help me to use Dynamic Multiple DataSources in Spring Data JPA?

DEBUG 18:20:44,975  [main]: Registered injected element on class [website.fedulov.aspect.ReadOnlyConnectionInterceptor]: AutowiredMethodElement for public void website.fedulov.aspect.ReadOnlyConnectionInterceptor.setOrder(int) - at org.springframework.beans.factory.annotation.InjectionMetadata.checkConfigMembers(InjectionMetadata.java:72)
DEBUG 18:20:44,976  [main]: Eagerly caching bean 'readOnlyInterceptor' to allow for resolving potential circular references - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:529)
DEBUG 18:20:44,976  [main]: Processing injected element of bean 'readOnlyInterceptor': AutowiredMethodElement for public void website.fedulov.aspect.ReadOnlyConnectionInterceptor.setOrder(int) - at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:86)
ReadOnlyConnectionInterceptor >>> order = 20
DEBUG 18:20:44,976  [main]: Finished creating instance of bean 'readOnlyInterceptor'                         - at org.springframework.beans.factory.support.DefaultListableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:484)
DEBUG 18:20:44,976  [main]: Returning cached instance of singleton bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importAwareProcessor' - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBean(AbstractBeanFactory.java:251)
DEBUG 18:20:44,977  [main]: Returning cached instance of singleton bean 'org.springframework.context.annotation.ConfigurationClassPostProcessor.enhancedConfigurationProcessor' - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBean(AbstractBeanFactory.java:251)
DEBUG 18:20:44,977  [main]: Returning cached instance of singleton bean 'org.springframework.orm.jpa.SharedEntityManagerCreator#0' - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBean(AbstractBeanFactory.java:251)
DEBUG 18:20:44,977  [main]: Returning cached instance of singleton bean 'org.springframework.context.event.internalEventListenerFactory' - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBean(AbstractBeanFactory.java:251)
DEBUG 18:20:44,978  [main]: Returning cached instance of singleton bean 'org.springframework.transaction.config.internalTransactionalEventListenerFactory' - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBean(AbstractBeanFactory.java:251)
DEBUG 18:20:45,003  [main]: Unable to locate LifecycleProcessor with name 'lifecycleProcessor': using default [org.springframework.context.support.DefaultLifecycleProcessor@17a9786] - at org.springframework.context.support.ClassPathXmlApplicationContext.initLifecycleProcessor(AbstractApplicationContext.java:769)
DEBUG 18:20:45,004  [main]: Returning cached instance of singleton bean 'lifecycleProcessor'                 - at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBean(AbstractBeanFactory.java:251)
DEBUG 18:20:45,006  [main]: Searching for key 'spring.liveBeansView.mbeanDomain' in [systemProperties]       - at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:81)
DEBUG 18:20:45,006  [main]: Searching for key 'spring.liveBeansView.mbeanDomain' in [systemEnvironment]      - at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:81)
DEBUG 18:20:45,007  [main]: Could not find key 'spring.liveBeansView.mbeanDomain' in any property source. Returning [null] - at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:103)
Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [website.fedulov.Main] is defined
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:372)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1066)
    at website.fedulov.Main.main(Main.java:35)

**Comment by afedulov** [comment]
Issue is closed by the latest commit.
